import localFont from "next/font/local";
import "./globals.css";
import SingleProduct from "./Sections/SingleProduct";
import Header from "./Sections/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className="font-[Poppins]">
      <Header />
      <SingleProduct />
      </body>
    </html>
  );
}
